#!/bin/bash
#Actual date Folder =  create timestamp dir with optional name linux/windows - http://safrm.net/projects/af
#author:  Miroslav Safr miroslav.safr@gmail.com
VERSION=NA                                                                   
VERSION_DATE=NA

DIRNAME=`date +%Y_%m_%d`
if [ "x$1" != "x" ]
then
    DIRNAME=${DIRNAME}_$1
fi

mkdir $DIRNAME
chmod ga+rw $DIRNAME
echo "$PWD/$DIRNAME"
cd $DIRNAME
