#!/bin/bash
#Actual date tXt file =  create timestamp text file with optional name linux/windows - http://safrm.net/projects/af
#author:  Miroslav Safr miroslav.safr@gmail.com
VERSION=NA
VERSION_DATE=NA


DATE=`date +%Y_%m_%d`
ID=1
FILENAME=$DATE_$ID

while : 
do
    if [ -f "./${DATE}_${ID}" ]; then
    	ID=$(($ID + 1)) ;
    else
        FILENAME=${DATE}_${ID}
        break;
    fi
done

if [ $# -gt 0 ]; then
    FILENAME=${FILENAME}_$1
fi
FILENAME=${FILENAME}.txt

touch $FILENAME
chmod ga+rw $FILENAME
echo "$PWD/$FILENAME"
if [ -n "$EDITOR" ]; then
    $EDITOR $FILENAME
else
    nano $FILENAME
fi

