'\" t
.\"     Title: aff
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 20141209_0936
.\"    Manual: Actual date Folder =  create timestamp dir with optional name linux/windows
.\"    Source: af 1.1.8
.\"  Language: English
.\"
.TH "AFF" "1" "20141209_0936" "af 1.1.8" "Actual date Folder = create t"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
aff \- Actual date Folder with timestamp
.SH "SYNOPSIS"
.HP \w'\fBaff\ [FOLDER_NAME]\fR\ 'u
\fBaff [FOLDER_NAME]\fR
.SH "DESCRIPTION"
.PP
Actual date Folder with timestamp
.PP
aff \&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&.\&. without commandline line parameter it creates first empty \&./2000_05_25_1 \&./2000_05_25_2
.PP
aff <my_folder> \&.\&. with string parameter it creates \&./2000_05_25_1_my_folder
.SH "FOLDER_NAME"
.PP
Name string used as suffix for directory name\&.
.SH "SEE ALSO"
.PP
\m[blue]\fB\%http://safrm.net/projects/af/\fR\m[]
.SH "AUTHOR"
.PP
Miroslav Šafr <miroslav\&.safr@gmail\&.com>
.SH "LICENSE"
.PP
LGPL2
.SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
